@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Feb 27 16:04:27 -0800 2024
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim l6_TB_behav -key {Behavioral:sim_1:Functional:l6_TB} -tclbatch l6_TB.tcl -view Z:/ELEN_122L/Lab6/lab_6/l6_TB_behav.wcfg -log simulate.log"
call xsim  l6_TB_behav -key {Behavioral:sim_1:Functional:l6_TB} -tclbatch l6_TB.tcl -view Z:/ELEN_122L/Lab6/lab_6/l6_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
